dev:
    env -u VIRTUAL_ENV uv run proxylens-server --reload

test:
    env -u VIRTUAL_ENV uv run pytest

test-watch:
    env -u VIRTUAL_ENV uv run ptw .

style-check:
    env -u VIRTUAL_ENV uv run black --check src tests

style-fix:
    env -u VIRTUAL_ENV uv run black src tests
